#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc desktop last.local -f

bspc config border_width         2
bspc config window_gap 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty desktop=^1 follow=on 
bspc rule -a kitty -e rtorrent desktop=^1 follow=on
bspc rule -a Chromium-browser desktop=^2 follow=on
bspc rule -a firefox desktop=^2 follow=on
bspc rule -a Pcmanfm desktop=^3 focus=on
bspc rule -a thunar desktop=^3
bspc rule -a Xfburn desktop=^4 follow=on
bspc rule -a thunderbird desktop=^4
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

###############Autostart#################
pgrep clipit &
feh --bg-scale /home/scott/dark.png &
lxpolkit &
~/.config/polybar/launch.sh &

sleep 0.05
polybar-msg cmd hide; bspc config top_padding +0

